[package]
name = "quickdeck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11" 
tokio = { version = "1", features = ["full"] }  
regex = "1.10.2"
webbrowser = "0.8.12"
